# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saeed Khodaparast
title: Machine Learning Engineer, Data Scientist
email: khodaparast2008@gmail.com
#website: www.github.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics

github_username:  mr3aeed
instagram_username: mr.3aeed
linkedin_username: saeed_khodaparast

# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Saeed. X
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Deep Reinforcement Learning Based Energy Efficient Multi-UAV Data Collection for IoT Networks
        # link: github.com/sproogen
        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          My Thesis

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Research and Teaching Assistant
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: York University
        caption: September 2019 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          I TAed multiple courses.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: York University
        caption: 2019 - 2021
        sub_title: MSc in Computer Engineering
        description: | # this will include new lines to allow paragraphs
          In my master's program, I focused on machine learning area and took courses to deepen my understanding in machine learning and data science. In my thesis, I applied deep reinforcement learning to the problem of data collection by UAVs in the IoT networks.
          
      - layout: left
        title: University of Tehran
        caption: 2014 - 2019
        sub_title: BSc Electrical Engineering, Minor Computer Engineering
        description: | # this will include new lines to allow paragraphs
          I started my undergrad studies in electrical engineering, which helped me to strenghten my math and engineering foundations. Then, to become more familiar with machine learning, I took two graduate courses and a minor in computer engineering. In my BSc research, I used auto encoders to predict users' locations in an indoor localization problem.

#         =
#        quote: >
#          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and #academic pedigree as a leading university in not just the US but also the world.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and science, I do photography wheneveer I get a chance (checkout my instagram). I love exploring the nature and hiking, as an outdoor kind of person :)


      ![freedom](images/insta.jpeg "freedom")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
